version: "3"
services:
  app:
    build: .
    links:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
