"""added is_expense field

Revision ID: 58e80d9c834b
Revises: aff532277930
Create Date: 2019-02-07 15:26:14.634778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e80d9c834b'
down_revision = 'aff532277930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_expense', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_expense')
    # ### end Alembic commands ###
