"""each expense, income, account is associated with user

Revision ID: 590282626a56
Revises: b1039b5c5091
Create Date: 2019-02-09 21:08:46.170033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590282626a56'
down_revision = 'b1039b5c5091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'])
    op.add_column('expense', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'user', ['user_id'], ['id'])
    op.add_column('income', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'user_id')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'user_id')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###
