"""Account table

Revision ID: 5a10ba73ca07
Revises: 58e80d9c834b
Create Date: 2019-02-08 15:17:55.092963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a10ba73ca07'
down_revision = '58e80d9c834b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('balance', sa.Float(precision=6), nullable=True),
    sa.Column('description', sa.String(length=128), default=None),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_account_type'), 'account', ['account_type'], unique=False)
    op.create_index(op.f('ix_account_description'), 'account', ['description'], unique=False)
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_index(op.f('ix_account_description'), table_name='account')
    op.drop_index(op.f('ix_account_account_type'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
