"""currency column in accounts

Revision ID: 90291a0307be
Revises: ae9cbacc0b5b
Create Date: 2019-02-11 14:17:16.953271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90291a0307be'
down_revision = 'ae9cbacc0b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('currency', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_account_currency'), 'account', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_currency'), table_name='account')
    op.drop_column('account', 'currency')
    # ### end Alembic commands ###
