"""incomes table

Revision ID: 9b2126223bff
Revises: c13a9a8342ad
Create Date: 2019-02-07 11:38:00.589767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2126223bff'
down_revision = 'c13a9a8342ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ammout', sa.Float(precision=6), nullable=True),
    sa.Column('description', sa.String(length=128), default=None),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_date'), 'income', ['date'], unique=False)
    op.create_index(op.f('ix_income_description'), 'income', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_description'), table_name='income')
    op.drop_index(op.f('ix_income_date'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
