"""user logins added city, country

Revision ID: b92435341690
Revises: da37346bfbd1
Create Date: 2019-02-04 21:21:35.625153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b92435341690'
down_revision = 'da37346bfbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_city'), 'user_login', ['city'], unique=False)
    op.create_index(op.f('ix_user_login_country'), 'user_login', ['country'], unique=False)
    op.create_index(op.f('ix_user_login_ip'), 'user_login', ['ip'], unique=False)
    op.create_index(op.f('ix_user_login_timestamp'), 'user_login', ['timestamp'], unique=False)
    op.drop_index('ix_user_logins_ip', table_name='user_logins')
    op.drop_index('ix_user_logins_location', table_name='user_logins')
    op.drop_index('ix_user_logins_timestamp', table_name='user_logins')
    op.drop_table('user_logins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_logins_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_logins_timestamp', 'user_logins', ['timestamp'], unique=False)
    op.create_index('ix_user_logins_location', 'user_logins', ['location'], unique=False)
    op.create_index('ix_user_logins_ip', 'user_logins', ['ip'], unique=False)
    op.drop_index(op.f('ix_user_login_timestamp'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_ip'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_country'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_city'), table_name='user_login')
    op.drop_table('user_login')
    # ### end Alembic commands ###
