"""name field in expeses

Revision ID: c13a9a8342ad
Revises: 50aff4a04ff5
Create Date: 2019-02-06 18:48:31.099737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c13a9a8342ad'
down_revision = '50aff4a04ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('expense', sa.Column('name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_expense_date'), 'expense', ['date'], unique=False)
    op.drop_index('ix_expense_timestamp', table_name='expense')
    op.drop_column('expense', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_expense_timestamp', 'expense', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_expense_date'), table_name='expense')
    op.drop_column('expense', 'name')
    op.drop_column('expense', 'date')
    # ### end Alembic commands ###
